### PR TITLE
version pinning due to problems with webpack 2

### PR DESCRIPTION
**Pull request by obestwalter**
see #14

### CODE REVIEW

**Comment by mmerickel** [comment]
Unfortunately this doesn't quite pin enough dependencies to work. Many of the loaders have had breaking changes and require webpack 2.0 in their latest versions as well.

**Comment by obestwalter** [comment]
@mmerickel it worked for me, when I tried it, but it's quite a while ago already and I am not dealing very much with JS packaging.

**Comment by mmerickel** [comment]
@obestwalter I understand... they've since released versions that cause it to break further. :-) I'm not saying it's your fault just that this PR doesn't do what is intended any longer.

**Comment by obestwalter** [comment]
Closing as obsolete.

**Pull request closed without merging**
